node/sync.go
get the entries in an eblock with 8 goroutines
not using waitgroups so we can abort early if an error is returned
=> multithreaded entry block sync

cmd/root.go, node/pegnet/pegnet.go
https://github.com/pegnet/pegnetd/blob/2c9be2dfa3d89981f40aaeffd909823611a87239/node/pegnet/pegnet.go#L35
This did not work on windows, so I'm just renaming $HOME to $USERPATH which does work. I also fixed the 'default' path to include the . that disappeared, bringing it back to consistency with the .toml config setting
=> fix paths on windows

cmd/root.go, config/locations.go, node/pegnet/pegnet.go
Added a flag for WAL mode, and ability to use arbitrary modes.
There might be better modes to use that can be discovered and
deployed with a config file vs a code update
Inspired by Adam's comment:
>Use write ahead log mode and you'll have even lower chance of corruption issues. Then nothing gets into the dB file until its committed. And sqlite can recover from a crash when the Wal didn't get written back to the db during close.
=> Add optional arbitrary sqlite modes

node/sync.go
Have trace info for when the tx is applied. It adds a function param to pass the tx context, but is helpful in debugging as we can see when the tx is found, and when it is applied.
Adding tracing for grading too.
=> Add extra trace info for when a tx is applied.

README.md
two very minor fixes
requiring go 1.13
and describing correct path of config location
=> fixing go version and config path

cmd/root.go, node/node.go, node/pegnet/addresses.go, node/pegnet/grading.go, node/pegnet/pegnet.go, node/sync.go
Add an activation height (TBD) for PEG conversions to go live, and also calculate the price of PEG when that height is reached or passed.
As a result of this discussion: https://github.com/pegnet/pegnet/pull/331#issuecomment-540130937 I have implemented pricing into pegnetd rather than the miner.
Where `PEG rate = (sum of all other asset capitalizations this block) / (sum of supply of all other assets last block)`. If this is off-base or I should be using bigints or something else, please correct me. This was just a first pass to get the code up here. Needs more testing and review.
=> Add PEG rate pricing after an activation height

node/pegnet/grading.go
There is a bug that was encountered syncing against mainnet, where the old PTickers that we dropped are not in the fat2 package (and really shouldn't be since theyll never be used for transactions).
But this meant that they were inserted as PTickerInvalid in the database, and with multiple assets that were dropped, this broke the unique constraint on the pn_rates table.
Switched back to using a ticker string in the InsertRates function to accommodate until we come up with a more elegant solution to managing old/new asset tickers and when they are valid
=> Fix Pegnet.InsertRates invalid/old PTicker bug

node/pegnet/grading.go
The v1 asset prices are not useful for any application data as no transactions or conversions need to access their values. This PR removes them from the SelectRates results
=> Remove old assets from the SelectRates function

node/pegnet/pegnet.go, node/pegnet/txhistory.go, node/pegnet/txhistory_util.go, node/pegnet/txhistory_util_test.go, node/sync.go, srv/methods.go, srv/params.go
I implemented a fairly rough tx history requests, but I'm not too sure about the implementation details, so I'm using this PR to get some feedback.
One of the fundamental issues was that a transactions have three dimensions, which meant splitting them up into three tables:
* `pn_transaction_history` this is the factom entryhash itself
* `pn_transaction_history_action` this corresponds to one of the transactions inside the txbatch
* `pn_transaction_history_action_data` this is one of the actions inside a transaction. for conversions there will only be a single one, for transfers there can be > 1
This table gets populated while syncing with all the relevant data (there is some redundancy for sake of ease of use). When a transaction is applied, the row's `executed` value is updated with the …
=> TX History API

node/sync.go
closes: #48 
Per #48, we really need better reporting. This PR does the following:
* If the node is up to date on boot, it will print: level=info msg="Node is up to date" height=XXXXXX
* If it's the intial sync, or there are > 1 blocks to sync, it will print a message before and after the sync loop: 
level=info msg="Starting sync job of XXX blocks" height=AAAAAA target=BBBBBBB
and
level=info msg="Finished sync job" blocks-synced=XXX height=BBBBBBB
* Instead of reporting sync stats every 50 blocks, it will report them every 15 seconds
* Under normal operations (not syncing more than one block at a time), print out a "status report" with current height every 6 blocks (height%6 == 0), which should be roughly once an hour
=> Improved Status Reports

node/pegnet/txhistory.go
continuing #82 
you're right about the index.
I used the test query
>EXPLAIN QUERY PLAN SELECT batch.history_id, batch.entry_hash, batch.height, batch.timestamp, batch.executed, tx.tx_index, tx.action_type, tx.from_address, tx.from_asset, tx.from_amount, tx.outputs, tx.to_asset, tx.to_amount FROM pn_history_lookup lookup, pn_history_txbatch batch, pn_history_transaction tx WHERE lookup.address = 'foobar' AND lookup.entry_hash = tx.entry_hash AND lookup.tx_index = tx.tx_index AND batch.entry_hash = tx.entry_hash ORDER BY batch.history_id ASC
to see what it was doing, and got:
SCAN TABLE... not good. The performance for this query was: 
`Result: 0 rows returned in 18996ms`
So I added an index for tx_index, and ran the `EXPLAIN` again:
The performance for this query was:
Result: 0 rows …
=> add index to history_transaction

cmd/api.go, node/pegnet/addresses.go, node/pegnet/grading.go, srv/methods.go, srv/params.go
Was doing this for PNMC, figured I might as well include the functionality in the cli.
Adds two api calls:
* get-rich-list which takes `count` and `asset` (count default is 100)
* get-global-rich-list which takes `count` (count default is 100)
I separated them because the logic for each is much different. Calculating the global rich list is more expensive than an asset rich list because I'm doing the conversions and sorting after the query. It is theoretically possible to build a query that does the conversions but due to the structure of the table, this was far easier to implement.
The asset-rich list returns a list of the top X addresses, the asset balance, and the pUSD equivalent value. The global list adds up the pUSD equivalent of all assets of that address and only returns the pUSD …
=> Rich list API request and cli command

node/pegnet/pegnet.go, node/pegnet/txhistory.go
close: #92 
This PR encompasses #92 and also includes DB migration for older databases. At startup, the node will check the structure of pn_history_lookup and attempt migration if the entry_hash column is an integer. 
I opted for an anonymous function so I could place the migration SQL statement close to the creation statement.
=> TX History Lookup: Change entry hash from integer to blob

cmd/root.go, cmd/util.go, cmd/util_test.go, fat/fat2/transaction.go, fat/fat2/transactionbatch.go, go.mod, go.sum, node/node.go, node/opr.go, node/pegnet/grading.go, node/pegnet/transaction_test.go, node/pegnet/txhistory.go, node/pegnet/txhistory_util.go, node/sync.go
Combines the PRs: https://github.com/pegnet/pegnetd/pull/94 and https://github.com/pegnet/pegnetd/pull/90
The 5K limit per block has an api change. Refunds are outputs. This means below is 100 pFCT -> PEG conversion. 
100 pFCT is the input.
2,500 PEG is the output
92.99712223 pFCT is the refund back to the original address
```
{
"actions": [
{
"executed": 131,
"fromaddress": "FA2w3564a1vuLqUbiwG8EB8anJJdyRyihArcBgjsfPSnyktMNFsy",
"fromamount": 10000000000,
"fromasset": "pFCT",
"hash": "34b97883391294767dd0b781767ac4c825bad94e2e20141b0eb0bc461306dcdf",
"height": 130,
"outputs": [
{
"address": "FA2w3564a1vuLqUbiwG8EB8anJJdyRyihArcBgjsfPSnyktMNFsy",
"amount": 9299712223
}
],
"timestamp": "2019-11-26T17:47:00-06:00",
"toamount": 250000000000,
"toasset": "PEG",
"txaction": 2,
"txid": …
```
=> Combined: Free float + 5K Limit

node/pegnet/grading.go
This does not affect mainnet as we had no 0 PEG supply blocks
My old comment if someone comes back to this PR in the future:
```
// This number is outrageously large since the total cap is the total
// assets * rates. Assets and rates are 1e8 notation, so a price
// of $1 puts 1 USD at a market cap of 1e8*1e8.
// A max int64 is `9223372036854775807` (cannot save top bit in sqlite)
// So with pUSD, 922.337203685 pUSD will overflow a int64 and break
// our system. If we have 0 PEG, just set the rate to 0. This means
// you can only create the first PEG from mining.
//
// This only affects local nets that burn before mining starts.
```
Tl;dr, we need to set to 0 to prevent an overflow
=> Correct 'uint64 values with high bit set are not supported'

cmd/api.go, node/pegnet/winners.go, srv/methods.go, srv/params.go
Added a cli/api call for finding the distribution of winning/graded oprs by miners
```
$ pegnetd minerdist -- -3000
Miner distribution for block range 223593 -> 226593 (3000 blocks)
Address                                               1st ID           # IDs   Win %    Graded %
-------                                               ------           -----   -----    --------
FA32WsZvT5Zg5RtdTPJi2gMV6MyoMR7UzHZSaq5T8o19P7ZVBLZh  MiningCenter     1      50.479%  48.295%
FA2uuco3tzXLJ6wuhkatfZCBVYzcFKVzAjD2iuHko4RynAwHWNUb  f2pool           1      34.549%  36.158%
FA1zvR2T4157PLegHPaTefSBFX4ocJ2jFoKjFTyokTKpK67EK93g  HedgehogsUnited  1       9.404%   9.609%
FA3hGHh2Jb1wtEd1jvwvaRM2LB6iB5ZNTVBXgEyhU8kaEeiDTES4  FoxAndRabbits    1       4.005%   4.284% …
```
=> Mining distro

cmd/root.go, config/locations.go, node/node.go, node/pegnet/admin.go, node/pegnet/admin_test.go, node/pegnet/metadata.go, node/pegnet/pegnet.go
If a pegnetd node is not updated late for a hard fork, meaning
a hard fork activates at height X, and the node is updated at X+1,
this code will prevent that node from launching. This is because
the node's state is incorrect. Preventing the node from launching
protects the user from an invalid state. A flag option is provided to
ignore this check if needed.
=> Implement a version checking function for hard forks

go.mod, go.sum
Pulls in the latest change to emyrk/factom@rcd_full, containing the timestamp signing fix: https://github.com/Emyrk/factom/pull/2
=> Update factom api dependency

node/pegnet/winners.go, srv/methods.go, srv/params.go
PR adds a new API method `get-graded`. Method accepts a single height as a parameter and returns a selection of fields from all graded OPRs for that height from the DB.
=> Add `get-graded` API method

fat/fat2/transactionbatch.go
Mark transactions as invalid that contain an input larger than int64 which can't be stored in SQLite.
=> [Hotfix] Check for int64 overflow

cmd/args.go, cmd/root.go, fat/fat2/pticker.go, go.mod, go.sum, node/node.go, node/opr.go, node/pegnet/addresses.go, node/pegnet/admin.go, node/pegnet/pegnet.go
Add v5 pAssets for Pegnet 2.0
1. Add additional V5 crypto assets.
HBAR, NEO, CRO, ETC, ONT, DOGE, VET, HT, ALGO, DGB
2. Add additional V5 currency assets.
AED, ARS, TWD, RWF, KES, UGX, TZS, BIF, ETB, NGN
=> Add v5 pAssets for Pegnet 2.0

node/burns.go, node/node.go, node/pegnet/pegnet.go, node/pegnet/txhistory.go, node/sync.go
Use `FA2BURNBABYBURNoooooooooooooooooooooooooooooooDGvNXy` as global burn address
1) One time operation to remove current funds in `NullifyBurnAddress` function which subtracts all values from burn address used to lock funds after attack
1.1) retrieve all balances for provided address
1.2) loop through issuance and subtract exact amount
1.3) should be executed before main sync logic because db will be locked later on
2) Makes `FA2BURNBAB...` global burn address. Adds functionality that doesn't add funds when they are transacted to the burn address
=> Adds global burn address. Set to zero balances at burn address

node/devs.go
Removes the 2% dev reward for Factoshi and credits that reward to the PegNet 2.5 address.
=> remove stat dev reward

cmd/root.go, config/locations.go, node/node.go, pegnetd-conf.toml
Initialize the chainIds based on network (`MainNet` or `TestNet`)
- TestNetwork Transaction chain: 
https://testnet.factoid.org/data?type=chain&key=55f41a66de87fc09ce4cdede4bc32eaee1ce8db203192564078c9875662d6189
- TestNetwork OraclePriceRecordChain: 
https://testnet.factoid.org/data?type=chain&key=f640503c1b7a6dfd58fa955d83cf0e974c22db4b5db1818f813d0f97a16809b2
- TestNetwork StakingPriceRecordChain:
https://testnet.factoid.org/data?type=chain&key=8efac3ae60d7506d31f0d9350e9cfbc00c90d28c817698efec6c5a7f6daf40e1
=> Add TestNet mode with chainID initialization

node/sync.go
- Purpose:
Increase the tolerance band range from 10% to 25% considering market prices & possible use cases between data providers and stakers. 
- How does it work?
Stakers' Oracle data will set the upper and lower limitation by 25%, and Miners will set the real prices if their values are included in the SPR tolerance band range.
=> Tolerance Band

cmd/api.go, node/node.go, node/pegnet/errors.go, node/sync.go
- PegNet disable small market cap pAssets conversion and allow only one way conversion.
pDCR,  pDGB, pDOGE,  pHBAR, pONT, pRVN, pBAT, pALGO, pBIF, pETB, pKES, pNGN, pRWF, pTZS, pUGX
=> [PIP-19] Stop conversions INTO pAssets that have small marketcap

node/sync.go
improves hash uniqueness so it doesn't overlap with other mock transaction on sync
=> remove tx hash overlaps when nullify burn

node/burns.go, node/mint.go, node/node.go, node/sync.go
- Add V204EnhanceActivation that indicates the activation of PegNet 2.0.4
- Add V204BurnMintTokenActivation that indicates the activation that burns remaining airdrop amount.
- MintTokensForBalance function that mint tokens for 2.0.4
- NullifyMintTokens that burns remaining funds from GlobalMintAddress
- Add GlobalMintAddress for AirDrop distribution
- Add MintTotalSupplyMap for AirDrop distribution
=> Version 2.0.4: Mint tokens, Nullify tokens with activation heights
