cmd/root.go
config/locations.go
node/burns.go
node/node.go
node/opr.go
node/pegnet/addresses.go
node/pegnet/grading.go
node/pegnet/metadata.go
node/pegnet/pegnet.go
node/sync.go

I'm going to use this as a "work in progress" branch so that you can review the changes. Doing single-feature branches doesn't make a lot of sense yet 
Changes:
Added --server (-s) and --wallet (-w) as flags to specify different endpoints. I'm not sure if your emyrk/factom branch is outdated but it doesn't match up with the FAT/factom branch when it comes to creating a new client. 
I changed the table create queries to include "IF NOT EXISTS" so we can get rid of the awkward double error check.
I created a metadata table that stores key-value settings. One of those settings is "synced", which is used to save the last synced height. When restarted, the node will pick up where it left off. If the setting doesn't exist, it starts from the hardcoded number. 
This is mostly copying code over …

WIP OPRs, Syncing, Config, more

---

cmd/root.go
node/pegnet/pegnet.go
node/sync.go
pegnetd-conf.toml

Move dblocation to `~/.pegnetd/mainnet/node.db`. We only support
mainnet atm, but this is future proofing.
Allow users to use non absolute paths from their home

Add FCT burns to balances

---

node/pegnet/pegnet.go
node/pegnet/txbatchholding.go
node/pegnet/txrelation.go

Add `"pn_address_transactions"` and `"pn_transaction_batch_holding"` tables with basic functions.
Integration into sync flow will happen in a different PR.

Finalized Transaction and Pending TransactionBatch DB Tables 

---

node/sync.go

Let's reward the miners for their hard work.

Give miners their rewards

---

cmd/api.go
cmd/args.go
cmd/root.go
cmd/tx.go
cmd/util.go
config/locations.go
fat/fat2/pticker.go
node/node.go
node/opr.go
node/pegnet/addresses.go
srv/methods.go
srv/params.go

Goal is to implement txs and conversions into the cli + api in this branch

Additional API and CLI work

---

node/pegnet/addresses.go
node/pegnet/pegnet.go
node/sync.go

Txs should fail or succeed in their entirety

Put all tx application checks up front

---

cmd/root.go
node/node.go
node/sync.go

Activation height is set to 500k atm. So you need the `--testing` flag to turn it on

Add tx/conv activation height

---

node/pegnet/pegnet.go
node/pegnet/txrelation.go
node/sync.go

The result_id was incorrect, and the address is sufficient for
our purposes

Switch from address_id to address

---

cmd/root.go

Create a config if none exists

---

cmd/api.go

closes: #47 
This PR adds the ability to burn FCT / convert FCT to pFCT to the pegnetd binary. Since the FAT library has very limited support for Transactions, I'm using @Emyrk's Transaction struct in order to manually build the transaction. (Thank you every much @Emyrk for including all the various marshaling functions).
Usage: `burn <FA-SOURCE> <AMOUNT>`
Requires the wallet to retrieve private key of fa-source and submits the transaction to factomd.
I successfully created a test FCT->pFCT conversion:
```
$ go run . burn FA3debugfUqPcG9ZbQAkjU8BSSJTGJDC6bAQMBYe3zTB4BktZxko 0.01
Successfully submitted the transaction
Transaction ID: 3bfb79454d6ec8f6053d5670c1f17a88c3ecebf5b1e13655f64689fb4c2da32b
```
https://explorer.factoid.org/transaction?txid=3bfb79454d6ec8f6053d5670c1f17a88c3ecebf5b1e1 …

Add FCT burn command

---

cmd/api.go
node/pegnet/transaction.go
node/pegnet/transaction_test.go
node/pegnet/txhistory.go
node/pegnet/txhistory_util.go
srv/methods.go
srv/params.go

For get-trasaction, require a txid with the format:
[TxIndex]-[Entryhash]
Add cli for get txs using the new txs api

Make get-transaction just use get-transactions api

---

cmd/api.go
node/pegnet/txhistory.go
node/pegnet/txhistory_util.go
srv/methods.go
srv/params.go

close: #80 
close: #77 
Adds to CLI:
- offset flag for "get txs" to specify the next offset
Adds to CLI & API:
- asset flag for transaction history to specify a specific asset to query

add asset filter to tx history api, offset to cli

---

build.bat

Adding the windows equivalent build.bat of build.sh.

[Properties] Windows Build

---

.travis.yml
Dockerfile
build.sh
cmd/api.go
cmd/root.go
cmd/util.go
config/version.go
node/opr.go
node/pegnet/pegnet.go
srv/methods.go
xgo/README.md

Add a `pegnetd properties` command
```
Pegnetd version and Properties
Build Verison: v0.2.0-87-g9e437eb
Build Commit: 9e437eb27a1a63dedde3c4481b06aeb68b755439
SQLite Version: 3.29.0
GoLang Version: go1.13.1
Factomd Version: 6.5.0
Factomd API Version: 2.0
Walletd Version: BuiltWithoutVersion
Walletd API Version: 2.0
```

Properties

---

pegnetd-conf.toml

Users are confused if they need to place an EC address here

Drop unused config option. 

---

.travis.yml

Travis was using the docker organization for login, rather than the user.

Use docker user for login

---

node/sync.go

Disable burn feature in pegnet 2.0

Disable burn for 2.0

---

node/devs.go
node/pegnet/txhistory.go
node/sync.go

Standalone Developer Rewards
- adds rewards for developers 
- developers are hardcoded in `node/devs.go` module
- set aside 2000 each block  for developer payouts
- pays 1 time a day same time PIP12 snapshotting happens
Links
- [Developer Rewards in PegNet](https://medium.com/@DJohnstonEC/developer-rewards-in-pegnet-dc490942e1ea)
- [PIPs conversions update](https://github.com/pegnet/pegnet/pull/360)

PIP 16 - Developer Rewards Mechanism

---

node/sync.go

dev reward skip when it has exception.

Dev reward payout exception

---

go.mod
go.sum
node/node.go
node/spr.go
node/sync.go

- SprSignatureActivation
- ComputeRCDFromPubkey

SprSignatureActivation

---

go.mod
go.sum

Hotfix: update pegnet dependency

---

node/sync.go

restore snapshot rate multiplicator 

---

node/node.go
node/spr.go

Add version 2.0.2 activation height: V202EnhanceActivation

ShuffleEntries for random entries

---

node/burns.go
node/sync.go

- Add version 0 asset rates function

Hotfix: GetAssetRates

---

node/burns.go
node/mint.go
node/node.go
node/sync.go

- Add V204EnhanceActivation that indicates the activation of PegNet 2.0.4
- Add V204BurnMintTokenActivation that indicates the activation that burns remaining airdrop amount.
- MintTokensForBalance function that mint tokens for 2.0.4
- NullifyMintTokens that burns remaining funds from GlobalMintAddress
- Add GlobalMintAddress for AirDrop distribution
- Add MintTotalSupplyMap for AirDrop distribution

Version 2.0.4
